name: Bump version and push

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Apply version bump (minor)
        run: 'npm version minor -m "release: %s"'

      - name: Push changes to deployment repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # Temporarily use the personal token
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: k8s-nest-app
          user-name: 'github-actions[bot]'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          # destination-github-username: eTF1-interne
          # destination-repository-name: mytf1-web-front-deployment
          # commit-message: Set `${{ inputs.deploy_target }}` image tag to `${{ inputs.version }}`
          # target-branch: main

      - id: set-version
        name: Output version change
        run: npm pkg get version
