name: Bump version and push

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: cache-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Apply version bump (minor)
        run: 'npm version minor -m "release: %s"'

      - name: Git push version bump
        run: git push -f origin develop

      - id: set-version
        name: Output version change
        run: npm pkg get version
