name: Bump version and push

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Apply version bump (minor)
        run: 'npm version minor -m "release: %s"'

      - name: Git push version bump
        run: git push origin develop --force

      - id: set-version
        name: Output version change
        run: npm pkg get version
