name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/echo1.yml

  # lint:
  #   needs: setup
  #   uses: ./.github/workflows/lint.yml

  # test:
  #   needs: setup
  #   uses: ./.github/workflows/test.yml

  # build:
  #   needs: [test, lint]
  #   uses: ./.github/workflows/build.yml

  # docker-build-push:
  #   needs: build
  #   uses: ./.github/workflows/docker-build-push.yml
  #   secrets: inherit
  #   with:
  #     environment: dev

  # deploy:
  #   if: github.ref_name == 'develop'
  #   needs: docker-build-push
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit
  #   with:
  #     environment: dev
