name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    tags:
      - '*'

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/build'
          key: cache-build-${{ github.sha }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: yabbal/k8s-nest-app
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - run: echo ${{ steps.meta.outputs.tags }}
      - run: echo ${{ steps.meta.outputs.labels }}
