name: CI

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging
    types: [closed]

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml

  deploy:
    uses: ./.github/workflows/echo.yml
