name: CI

on:
  push:
    branches:
      - staging

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  thejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will show on every push staging"
