name: Bump version project

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  staging:
    needs: setup
    if: 'github.event.pull_request.merged == true'
    uses: ./.github/workflows/bump-push.yml
