name: CI

on:
  push:
    branches:
      - staging

  pull_request:
    branches:
      - staging
    types: [closed]

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/echo1.yml

  deploy:
    uses: ./.github/workflows/echo.yml
