name: CI

on:
  pull_request:
    types: [closed]
    branches:
      - staging

jobs:
  thejob:
    if: 'github.event.pull_request.merged == true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This will only show if the PR has been merged (and not if it was closed without merging)."
