name: Dev

on:
  push:
    branches:
      - develop

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: setup
    uses: ./.github/workflows/test.yml
