name: Docker build and push

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  ECR_REPOSITORY: yabbal/k8s-nest-app

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/build'
          key: cache-build-${{ github.sha }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: ${{ env.ECR_REPOSITORY }}
          tags: |
            ${{ inputs.environment == 'dev' && 'type=sha,prefix=,format=long' || 'type=semver,pattern={{version}}' }}

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yabbal
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update label preview
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event_name == 'pull_request'
        with:
          labels: preview
