name: Update Deployment repository

on:
  workflow_call:
    inputs:
      deploy_target:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ECR_REPOSITORY: yabbal/k8s-nest-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ECR_REPOSITORY }}
          tags: |
            ${{ inputs.environment == 'dev' && github.event_name == 'pull_request' && 'type=ref,event=pr' || inputs.environment == 'dev' && 'type=sha' || 'type=semver,pattern={{version}}' }}

      - name: Checkout deployment repo
        uses: actions/checkout@v3
        with:
          repository: yabbal/k8s-nest-deployment
          ref: main
          path: deployment
          token: ${{ secrets.PAT }}

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update deployed version
        run: |
          (cd deployment/overlays/${{ inputs.deploy_target }}/ && kustomize edit set image "nest-app=${{ env.ECR_REPOSITORY }}:${{ steps.meta.outputs.version}}")

      - name: Push changes to deployment repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # Temporarily use the personal token
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: deployment
          user-name: 'github-actions[bot]'
          user-email: 'github-actions[bot]@users.noreply.github.com'
          destination-github-username: yabbal
          destination-repository-name: k8s-nest-deployment
          commit-message: Set `${{ inputs.deploy_target }}` image tag to `${{ env.ECR_REPOSITORY }}:${{ steps.meta.outputs.version}}`
          target-branch: main
